Facebook Accounts
bjoshua18/schedule_app pull request #1
Opened 2021-03-12 12:21 UTC by bjoshua18

Implementamos la vinculación de cuentas de facebook
Creamos los tests de los modelos

2021-03-15 14:54 UTC, alejandrogq requested changes

2021-03-15 14:54 UTC, alejandrogq commented on app/controllers/facebook_accounts_controller.rb
> +    @facebook_account.destroy
Y si esto devuelve false?

2021-03-15 14:54 UTC, alejandrogq commented on app/controllers/posts_controller.rb
> +    @posts = Current.user.posts.order_by(publish_at: 1)
Has creado un indice para el campo publish_at

2021-03-15 14:54 UTC, alejandrogq commented on app/controllers/posts_controller.rb
> +    @post.destroy
Si falla el destroy?

2021-03-15 14:54 UTC, alejandrogq commented on app/models/post.rb
> +    # tweet = twitter_account.client.update_with_media(body, File.new(Rails.root.join('app', 'assets', 'images', 'page_flow.png')))
Esto se quedo comentado

2021-03-15 14:54 UTC, alejandrogq commented on app/models/user.rb
>    has_many :posts
Post es solo de facebook?

2021-03-15 14:54 UTC, alejandrogq commented on app/views/facebook_accounts/index.html.haml
> +      -# = link_to acc.name, acc.account.get_object('me'), class: 'link-primary', target: '_blank'
comentado

2021-03-15 14:54 UTC, alejandrogq commented on app/views/sessions/new.html.haml
>  = form_with url: login_path do |form|
Usar simple_form?

2021-03-15 16:08 UTC, bjoshua18 commented on app/controllers/posts_controller.rb
> +    @posts = Current.user.posts.order_by(publish_at: 1)
Es el index donde se listan todos los posts por orden de fecha de publicación

2021-03-15 16:41 UTC, alejandrogq commented on app/controllers/posts_controller.rb
> +    @posts = Current.user.posts.order_by(publish_at: 1)
No me has entendido, un indice en la base de datos

2021-03-15 16:49 UTC, bjoshua18 commented on app/models/user.rb
>    has_many :posts
El modelo Post tiene que ser refactorizado. Tenemos pendiente cambiar la estructura de los accounts, que TwitterAccount y FacebookAccount hereden de una superclase Account, así, Post pertenece a un account mas genérico

2021-03-16 06:34 UTC, bjoshua18 commented on app/controllers/posts_controller.rb
> +    @posts = Current.user.posts.order_by(publish_at: 1)
Ok, ¿un índice para publish_at para que la consulta order_by sea más rápida?

```
# post.rb
index({publish_at: -1})
```

2021-03-16 08:37 UTC, merged

2021-03-16 10:35 UTC, alejandrogq commented on app/models/user.rb
>    has_many :posts
ok